### PR TITLE
doc: Add a page covering printer setup and firewall issues

### PR DESCRIPTION
**Pull request by gwhitney**
An initial draft, as discussed in #41. A few notes:

* The new page printersetc.md is not linked in to the outline in any way, so it won't yet actually show up (and in fact, I think might cause an error or warning) when building the documentation.
* The draft is quite possibly too verbose/chatty, as I tend in that direction; if so, please just let me know and I will try to streamline.
* I wasn't quite sure what level of detail to go to, and in particular if I should include screenshots; I left in a "warning" asking about that point. Again, happy to revise if given some feedback.
* Finally, a few of the details (such as what services to authorize to allow printing through a firewall) are a bit fuzzy, because as I mentioned, I am not actually much of an expert on this topic -- I just wanted to get my printer working.

Hope this helps and let me know how I can improve this further.

### CODE REVIEW

**Review by why-not-try-calmer — CHANGES_REQUESTED** [review]
Hey Glenn thanks, this is an excellent first PR and I am looking forward to receiving more like it.

That said, I get it why you warned against its being a bit chatty. I have a variation of the same symptoms myself and something that helps me is to use:
- shorter sentences;
- shorter paragraphs;
- shorter sections.

I think that would be the first big step in the right direction. Ideally entire document is:
1. exposing a problem
2. identifying beneficiaries of a solution
3. walking them to the solution. 

The schema applies recursively: every part/section/subsection should be written with this structure in mind. Feel free to point it out if I / we have failed to apply this recipe to other parts of the documentation, because that's really the most important thing. :)

I won't bash your ears with more suggestions because this one means already some work, but I'd also suggest to be clear on the "ingredients" that you recipes presuppose. This is especially important since we're talking hardware here. So it should never happen that someone has to read more than 10% of a particular section/subsection before realizing that they are missing 1 key element that will block them. 

Thus my second recommendation would be to implement the first recommendation by clearly delineating all the presuppositions/non-negotiable items that the reader needs to have from the outset in order to carry out the instructions in any part of the document.

Hope it's useful. Cheers!

**Comment by gwhitney** [comment]
Yeah, I figured, but thought I'd let your review the style/content before editing. Any better now? Specific suggestions are especially welcome at this point (where I've now spent time roughly equal to solving the issue in the first place -- I am definitely committed to helping others by getting in some documentation on this, but of course I just have to squeeze this in in my spare time, thanks for understanding).

**Comment by gwhitney** [comment]
I'm sorry I hope I didn't give offense with my comment about the time it was taking. Getting this point into the docs is important to me, so please just let me know what you think of the revised draft and how I can improve it further to the point where it can be merged.

**Comment by why-not-try-calmer** [comment]
> I'm sorry I hope I didn't give offense with my comment about the time it was taking. Getting this point into the docs is important to me, so please just let me know what you think of the revised draft and how I can improve it further to the point where it can be merged.

Hey Gwen, my bad I took some days off to work on others things and I forgot to notify all my interlocutors. Don't worry, we will get this through, but the major blocker for me is that it looks too much like prose and not enough like a list (I love lists, I really do!). 

Could you try to make everything more list-like? I'd like to insist on the recursive pattern identified earlier -- points (1-3) in my previous comment.

Cheers!

**Comment by gwhitney** [comment]
My apologies for the long hiatus, my other commitments became more pressing. Is this any better? I've tried to be pretty economical in expression. I think the article is now fairly information dense and reasonably systematic. But of course if you need further edits let me know.

**Review by why-not-try-calmer — CHANGES_REQUESTED** [review]
This is much better already. I have made some changes I would like to submit to you guys at https://github.com/openSUSE/openSUSE-docs-revamped-temp/tree/adrien/fix/ghwhitney-printer_firewall. Let me know!

**Comment by gwhitney** [comment]
Awesome. Thanks so much for moving this forward. The only comment I have on the revised version in the branch you link to above is that the first sentence of the "Configuring your printer" section now says that "getting it to show up.. is the whole story" when what I think should be said is that "getting it to show up is *not necessarily* the whole story." I have definitely encountered wrinkles even after I've gotten the printer to show up.  Otherwise I feel like your revised version would be an excellent addition to the opensuse docs, thanks!

**Comment by why-not-try-calmer** [comment]
Let's finish the work there (#52) if you guys don't mind.

**Pull request closed without merging**
