### PR TITLE
Allow-vendor-change & packman hell

### PR DESCRIPTION
**Pull request by why-not-try-calmer**
- patch recommendations about installing codecs manually

Can someone review me on this?

### CODE REVIEW

**Comment by Idesmi** [comment]
The procedure you explain in the Manual section isn't the best way to change vendor from `openSUSE` to `packman`.
I would also advise against editing `/etc/zypp.conf` to allow automatic vendor change.

What I would rather do:
* add Packman repository with alias `packman` and higher priority
* `zypper dup --from packman --allow-vendor-change`

Packages now moved to packman will stay on packman forever, unless they are removed from the packman repo at some point.
In that case, the zypper resolver will ask the user if they want to switch vendor while upgrading.

**Comment by why-not-try-calmer** [comment]
> The procedure you explain in the Manual section isn't the best way to change vendor from `openSUSE` to `packman`.
> I would also advise against editing `/etc/zypp.conf` to allow automatic vendor change.
> 
> What I would rather do:
> 
> * add Packman repository with alias `packman` and higher priority
> * `zypper dup --from packman --allow-vendor-change`
> 
> Packages now moved to packman will stay on packman forever, unless they are removed from the packman repo at some point.
> In that case, the zypper resolver will ask the user if they want to switch vendor while upgrading.
> 
> I don't think the addition coming with this merge is helpful :)

Thanks, adding Packman with higher priority cannot be an improvement though, as said often by the author of this [reddit comment](https://www.reddit.com/r/openSUSE/comments/543l68/what_is_the_best_way_to_get_all_of_the_tumbleweed/d7yqgqb?utm_source=share&utm_medium=web2x&context=3). 

The other part is promising though, but I have a question:

- If the user adds the packman repo, does the user has to always remember to do `zypper dup -- from packman --allow-vendor-change to update safely?

**Comment by Idesmi** [comment]
> If the user follows your method, does the user have to always remember to do zypper dup --from packman --allow-vendor-change to update their system safely?

No, because packages don't switch vendor on their own, with default zypper configuration. You just need to set codecs packages to be serviced by Packman repositories once, and they'll always update from it.

> If we are talking improvement, isn't
> * install packman packages only with zypper install --from <alias> <packages>
> * update with zypper dup (no extra flag needed)
> more simple and less error-prone?

It's a good alternative, BUT it leaves out any codec package already installed and vendored by openSUSE.
If you do not trust priority alone, then these two commands you've written here are better as:
```
zypper install --from <alias> <packages>
zypper dup --from <alias> --allow-vendor-change
```
Theoretically though, if a package is found both in the official and in the packman repo *at the same version*, the repository with the highest priority is chosen, making `install --from <alias>` redundant.

**Comment by why-not-try-calmer** [comment]
> > If the user follows your method, does the user have to always remember to do zypper dup --from packman --allow-vendor-change to update their system safely?
> 
> No, because packages don't switch vendor on their own, with default zypper configuration. You just need to set codecs packages to be serviced by Packman repositories once, and they'll always update from it.
> 
> > If we are talking improvement, isn't
> > 
> > * install packman packages only with zypper install --from
> > * update with zypper dup (no extra flag needed)
> >   more simple and less error-prone?
> 
> It's a good alternative, BUT it leaves out any codec package _**already**_ installed and vendored by openSUSE.
> If you do not trust priority alone, then these two commands you've written here are better as:
> 
> ```
> zypper install --from <alias> <packages>
> zypper dup --from <alias> --allow-vendor-change
> ```
> 
> Theoretically though, if a package is found both in the official and in the packman repo _at the same version_, the repository with the highest priority is chosen, making `install --from <alias>` redundant.

Thanks, that's very helpful! My main objective it to have instructions that require the least keytrokes (over time) and are the safest to use. This means that I would like avoid anything that would r_equire_ the user to remember to append flags when running update commands. I think this is very risky. So here is the list of constraints I would like to meet:
- no change in repo priority (because risky)
- no flags when doing `zypper dup` as part of the user ordinary routine after packmain has been installed (though flags are OK if this is just for installing packman packages)
- functional and safe installation of packman stuff.

Is there something you can propose that satisfies these contraints? What would come the closest in your opinion?

**Comment by Idesmi** [comment]
I think the optimal procedure is to follow exactly [what `opi` does](https://github.com/openSUSE/opi/blob/master/opi/plugins/packman.py), since it is an openSUSE project:

```
sudo zypper ar -cfp 90 'https://ftp.gwdg.de/pub/linux/misc/packman/suse/<distribution>_<project>/' packman
sudo zypper in --from packman ffmpeg gstreamer-plugins-bad gstreamer-plugins-libav gstreamer-plugins-ugly libavcodec-full vlc-codecs
sudo zypper in gstreamer-plugins-good gstreamer-plugins-good-extra
```

Optionally, `zypper dup --from packman` at the end, but we can also omit it.

**Comment by why-not-try-calmer** [comment]
> I think the optimal procedure is to follow exactly [what `opi` does](https://github.com/openSUSE/opi/blob/master/opi/plugins/packman.py), since it is an openSUSE project:
> 
> ```
> sudo zypper ar -cfp 90 'https://ftp.gwdg.de/pub/linux/misc/packman/suse/<distribution>_<project>/' packman
> sudo zypper in --from packman ffmpeg gstreamer-plugins-bad gstreamer-plugins-libav gstreamer-plugins-ugly libavcodec-full vlc-codecs
> sudo zypper in gstreamer-plugins-good gstreamer-plugins-good-extra
> ```
> 
> Optionally, `zypper dup --from packman` at the end, but we can also omit it.

Well if the only acceptable method mimicks the script let's not support any manual installation method.

**Comment by Idesmi** [comment]
> Well if the only acceptable method mimicks the script let's not support any manual installation method.

It's not the only acceptable method; I'm a normal contributor like you, not an authority.
It's true that manual instruction makes sense when the automated way does too much or does it in a way that does not work everywhere, which are not issues here, but we can choose to leave it so that readers know what the automated way does. Your choice.

**Comment by why-not-try-calmer** [comment]
> > Well if the only acceptable method mimicks the script let's not support any manual installation method.
> 
> It's not the only acceptable method; I'm a normal contributor like you, not an authority.
> It's true that manual instruction makes sense when the automated way does too much or does it in a way that does not work everywhere, which are not issues here, but we can choose to leave it so that readers know what the automated way does. Your choice.

We can absolutely copy-paste the zypper commands that OPI runs. No problem with that. Or we can doument/explain what these commands do. No problem with that either. My problem is that the zypper commands that OPI runs are superior to any alternative as far as "avoiding packman hell" is concerned. In other words, any alternative has an increase probability of creating conflicts that the user will have to resolve manually. For having seen that happen quite frequently on the support channels, I think it's a good idea to not cover alternative for the same use case which are worse in all relevant aspects.

Would you agree with that?

**Review by Idesmi — APPROVED** [review]

**Comment by why-not-try-calmer** [comment]
I am leaving this PR open even after the #39 merge so that Attila can suggest improvements or make criticism. I will include them.

**Pull request merged**
