### PR TITLE
Content power management

### PR DESCRIPTION
**Pull request by Ethanol6**
- fix minor spelling and grammar issues

### CODE REVIEW

**Comment by why-not-try-calmer** [comment]
Thanks for your patience!

**Comment by Ethanol6** [comment]
@why-not-try-calmer please look at line 41. It is like one thought began the sentence and never got a chance to finish. I couldn't decide what it was supposed to say.

**Comment by why-not-try-calmer** [comment]
@Ethanol6 Should be fixed no. Can you confirm?

**Comment by Ethanol6** [comment]
looks better now! Cheers!

**Pull request merged**
