### PR TITLE
Update microos_getting_started.md

### PR DESCRIPTION
**Pull request by syds-git**
additional steps for Toolbox apps

### CODE REVIEW

**Comment by why-not-try-calmer** [comment]
Thank you very much!

**Comment by syds-git** [comment]
no review necessary, this comes directly from Dario https://t.me/opensuse/176163 also tested it myself.

**Comment by syds-git** [comment]
plus the other stuff that i'm deletting, was stuff that was in the manual before, but not really necessary anymore (that's why i had already moved it down and called it old stuff)

**Comment by why-not-try-calmer** [comment]
> no review necessary, this comes directly from Dario https://t.me/opensuse/176163 also tested it myself.

Good, merging then!

**Pull request merged**
