### PR TITLE
fix formatting

### PR DESCRIPTION
**Pull request by Idesmi**

### CODE REVIEW

**Review by why-not-try-calmer — APPROVED** [review]
thank you very much

**Comment by why-not-try-calmer** [comment]
I would be glad if there were more people becoming maintainers of this repository. Are you interested @Idesmi?

**Comment by Idesmi** [comment]
@why-not-try-calmer I am interested and I have the knowledge of a everyday openSUSE tinkerer, but I'm also quite sporadic in contributions.

I can write the whole or the prompt to some of the new articles listed in the TODO.

**Comment by why-not-try-calmer** [comment]
> @why-not-try-calmer I am interested and I have the knowledge of a everyday openSUSE tinkerer, but I'm also quite sporadic in contributions.
> 
> I can write the whole or the prompt to some of the new articles listed in the TODO.

Are you familiar with basic git commands? Not that it's mandadory, just that it helps. If you don't we can show the little you need to know.

@apinter Can you visualize who is "super" admin in here? It would be nice to give @Idesmi write rights :)

**Comment by Idesmi** [comment]
I am familiar with git, thank you for the helpfulness

**Pull request merged**
